// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _Array2Mat_HH_
#define _Array2Mat_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct Array2Mat : public sc_module {
    // Port declarations 28
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_in< sc_logic > start_full_n;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_logic > start_out;
    sc_out< sc_logic > start_write;
    sc_out< sc_lv<5> > fb_address0;
    sc_out< sc_logic > fb_ce0;
    sc_in< sc_lv<32> > fb_q0;
    sc_in< sc_lv<5> > img_rows_V_dout;
    sc_in< sc_logic > img_rows_V_empty_n;
    sc_out< sc_logic > img_rows_V_read;
    sc_in< sc_lv<5> > img_cols_V_dout;
    sc_in< sc_logic > img_cols_V_empty_n;
    sc_out< sc_logic > img_cols_V_read;
    sc_out< sc_lv<8> > img_data_stream_V_din;
    sc_in< sc_logic > img_data_stream_V_full_n;
    sc_out< sc_logic > img_data_stream_V_write;
    sc_out< sc_lv<5> > img_rows_V_out_din;
    sc_in< sc_logic > img_rows_V_out_full_n;
    sc_out< sc_logic > img_rows_V_out_write;
    sc_out< sc_lv<5> > img_cols_V_out_din;
    sc_in< sc_logic > img_cols_V_out_full_n;
    sc_out< sc_logic > img_cols_V_out_write;


    // Module declarations
    Array2Mat(sc_module_name name);
    SC_HAS_PROCESS(Array2Mat);

    ~Array2Mat();

    sc_trace_file* mVcdFile;

    sc_signal< sc_logic > real_start;
    sc_signal< sc_logic > start_once_reg;
    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<4> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > internal_ap_ready;
    sc_signal< sc_logic > img_rows_V_blk_n;
    sc_signal< sc_logic > img_cols_V_blk_n;
    sc_signal< sc_logic > img_data_stream_V_blk_n;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter2;
    sc_signal< bool > ap_block_pp0_stage0;
    sc_signal< sc_lv<1> > icmp_ln175_reg_409;
    sc_signal< sc_lv<1> > icmp_ln175_reg_409_pp0_iter1_reg;
    sc_signal< sc_logic > img_rows_V_out_blk_n;
    sc_signal< sc_logic > img_cols_V_out_blk_n;
    sc_signal< sc_lv<32> > t_V_3_reg_145;
    sc_signal< sc_lv<32> > rows_V_fu_156_p1;
    sc_signal< sc_lv<32> > rows_V_reg_375;
    sc_signal< bool > ap_block_state1;
    sc_signal< sc_lv<32> > cols_V_fu_160_p1;
    sc_signal< sc_lv<32> > cols_V_reg_380;
    sc_signal< sc_lv<1> > icmp_ln174_fu_164_p2;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<32> > row_V_fu_169_p2;
    sc_signal< sc_lv<32> > row_V_reg_389;
    sc_signal< sc_lv<8> > shl_ln_fu_179_p3;
    sc_signal< sc_lv<8> > shl_ln_reg_394;
    sc_signal< sc_lv<8> > trunc_ln1352_1_fu_191_p3;
    sc_signal< sc_lv<8> > trunc_ln1352_1_reg_399;
    sc_signal< sc_lv<2> > tmp_s_fu_203_p3;
    sc_signal< sc_lv<2> > tmp_s_reg_404;
    sc_signal< sc_lv<1> > icmp_ln175_fu_211_p2;
    sc_signal< sc_logic > ap_CS_fsm_pp0_stage0;
    sc_signal< bool > ap_block_state3_pp0_stage0_iter0;
    sc_signal< bool > ap_block_state4_pp0_stage0_iter1;
    sc_signal< bool > ap_block_state5_pp0_stage0_iter2;
    sc_signal< bool > ap_block_pp0_stage0_11001;
    sc_signal< sc_lv<32> > col_V_fu_216_p2;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter0;
    sc_signal< sc_lv<2> > trunc_ln178_2_i1_i1_fu_255_p2;
    sc_signal< sc_lv<2> > trunc_ln178_2_i1_i1_reg_423;
    sc_signal< sc_lv<8> > fb_pix_fu_371_p1;
    sc_signal< sc_lv<8> > fb_pix_reg_428;
    sc_signal< bool > ap_block_pp0_stage0_subdone;
    sc_signal< sc_logic > ap_condition_pp0_exit_iter0_state3;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter1;
    sc_signal< sc_lv<32> > t_V_reg_134;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<64> > zext_ln178_fu_246_p1;
    sc_signal< bool > ap_block_pp0_stage0_01001;
    sc_signal< sc_lv<5> > rows_V_fu_156_p0;
    sc_signal< sc_lv<5> > cols_V_fu_160_p0;
    sc_signal< sc_lv<5> > trunc_ln1352_fu_175_p1;
    sc_signal< sc_lv<7> > trunc_ln1352_2_fu_187_p1;
    sc_signal< sc_lv<1> > empty_76_fu_199_p1;
    sc_signal< sc_lv<8> > trunc_ln178_fu_222_p1;
    sc_signal< sc_lv<8> > add_ln178_fu_226_p2;
    sc_signal< sc_lv<8> > add_ln178_1_fu_231_p2;
    sc_signal< sc_lv<6> > lshr_ln_fu_236_p4;
    sc_signal< sc_lv<2> > empty_78_fu_251_p1;
    sc_signal< sc_lv<5> > tmp_1_fu_260_p3;
    sc_signal< sc_lv<5> > empty_79_fu_267_p2;
    sc_signal< sc_lv<6> > zext_ln178_1_fu_279_p1;
    sc_signal< sc_lv<6> > zext_ln178_2_fu_283_p1;
    sc_signal< sc_lv<1> > icmp_ln178_fu_273_p2;
    sc_signal< sc_lv<6> > sub_ln178_fu_297_p2;
    sc_signal< sc_lv<6> > sub_ln178_1_fu_309_p2;
    sc_signal< sc_lv<32> > tmp_fu_287_p4;
    sc_signal< sc_lv<6> > xor_ln178_fu_303_p2;
    sc_signal< sc_lv<6> > select_ln178_fu_315_p3;
    sc_signal< sc_lv<6> > select_ln178_2_fu_331_p3;
    sc_signal< sc_lv<6> > sub_ln178_2_fu_339_p2;
    sc_signal< sc_lv<32> > select_ln178_1_fu_323_p3;
    sc_signal< sc_lv<32> > zext_ln178_3_fu_345_p1;
    sc_signal< sc_lv<32> > zext_ln178_4_fu_349_p1;
    sc_signal< sc_lv<32> > lshr_ln178_fu_353_p2;
    sc_signal< sc_lv<32> > lshr_ln178_1_fu_359_p2;
    sc_signal< sc_lv<32> > and_ln178_fu_365_p2;
    sc_signal< sc_lv<4> > ap_NS_fsm;
    sc_signal< sc_logic > ap_idle_pp0;
    sc_signal< sc_logic > ap_enable_pp0;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<4> ap_ST_fsm_state1;
    static const sc_lv<4> ap_ST_fsm_state2;
    static const sc_lv<4> ap_ST_fsm_pp0_stage0;
    static const sc_lv<4> ap_ST_fsm_state6;
    static const bool ap_const_boolean_1;
    static const sc_lv<32> ap_const_lv32_0;
    static const bool ap_const_boolean_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<5> ap_const_lv5_7;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<6> ap_const_lv6_1F;
    static const sc_lv<32> ap_const_lv32_FFFFFFFF;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_add_ln178_1_fu_231_p2();
    void thread_add_ln178_fu_226_p2();
    void thread_and_ln178_fu_365_p2();
    void thread_ap_CS_fsm_pp0_stage0();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state6();
    void thread_ap_block_pp0_stage0();
    void thread_ap_block_pp0_stage0_01001();
    void thread_ap_block_pp0_stage0_11001();
    void thread_ap_block_pp0_stage0_subdone();
    void thread_ap_block_state1();
    void thread_ap_block_state3_pp0_stage0_iter0();
    void thread_ap_block_state4_pp0_stage0_iter1();
    void thread_ap_block_state5_pp0_stage0_iter2();
    void thread_ap_condition_pp0_exit_iter0_state3();
    void thread_ap_done();
    void thread_ap_enable_pp0();
    void thread_ap_idle();
    void thread_ap_idle_pp0();
    void thread_ap_ready();
    void thread_col_V_fu_216_p2();
    void thread_cols_V_fu_160_p0();
    void thread_cols_V_fu_160_p1();
    void thread_empty_76_fu_199_p1();
    void thread_empty_78_fu_251_p1();
    void thread_empty_79_fu_267_p2();
    void thread_fb_address0();
    void thread_fb_ce0();
    void thread_fb_pix_fu_371_p1();
    void thread_icmp_ln174_fu_164_p2();
    void thread_icmp_ln175_fu_211_p2();
    void thread_icmp_ln178_fu_273_p2();
    void thread_img_cols_V_blk_n();
    void thread_img_cols_V_out_blk_n();
    void thread_img_cols_V_out_din();
    void thread_img_cols_V_out_write();
    void thread_img_cols_V_read();
    void thread_img_data_stream_V_blk_n();
    void thread_img_data_stream_V_din();
    void thread_img_data_stream_V_write();
    void thread_img_rows_V_blk_n();
    void thread_img_rows_V_out_blk_n();
    void thread_img_rows_V_out_din();
    void thread_img_rows_V_out_write();
    void thread_img_rows_V_read();
    void thread_internal_ap_ready();
    void thread_lshr_ln178_1_fu_359_p2();
    void thread_lshr_ln178_fu_353_p2();
    void thread_lshr_ln_fu_236_p4();
    void thread_real_start();
    void thread_row_V_fu_169_p2();
    void thread_rows_V_fu_156_p0();
    void thread_rows_V_fu_156_p1();
    void thread_select_ln178_1_fu_323_p3();
    void thread_select_ln178_2_fu_331_p3();
    void thread_select_ln178_fu_315_p3();
    void thread_shl_ln_fu_179_p3();
    void thread_start_out();
    void thread_start_write();
    void thread_sub_ln178_1_fu_309_p2();
    void thread_sub_ln178_2_fu_339_p2();
    void thread_sub_ln178_fu_297_p2();
    void thread_tmp_1_fu_260_p3();
    void thread_tmp_fu_287_p4();
    void thread_tmp_s_fu_203_p3();
    void thread_trunc_ln1352_1_fu_191_p3();
    void thread_trunc_ln1352_2_fu_187_p1();
    void thread_trunc_ln1352_fu_175_p1();
    void thread_trunc_ln178_2_i1_i1_fu_255_p2();
    void thread_trunc_ln178_fu_222_p1();
    void thread_xor_ln178_fu_303_p2();
    void thread_zext_ln178_1_fu_279_p1();
    void thread_zext_ln178_2_fu_283_p1();
    void thread_zext_ln178_3_fu_345_p1();
    void thread_zext_ln178_4_fu_349_p1();
    void thread_zext_ln178_fu_246_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
