-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Mat2AXIM is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    img_data_stream_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    img_data_stream_V_empty_n : IN STD_LOGIC;
    img_data_stream_V_read : OUT STD_LOGIC;
    fb_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    fb_ce0 : OUT STD_LOGIC;
    fb_we0 : OUT STD_LOGIC;
    fb_d0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of Mat2AXIM is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal grp_Mat2Array_fu_38_ap_start : STD_LOGIC;
    signal grp_Mat2Array_fu_38_ap_done : STD_LOGIC;
    signal grp_Mat2Array_fu_38_ap_idle : STD_LOGIC;
    signal grp_Mat2Array_fu_38_ap_ready : STD_LOGIC;
    signal grp_Mat2Array_fu_38_img_data_stream_V_read : STD_LOGIC;
    signal grp_Mat2Array_fu_38_fb_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_Mat2Array_fu_38_fb_ce0 : STD_LOGIC;
    signal grp_Mat2Array_fu_38_fb_we0 : STD_LOGIC;
    signal grp_Mat2Array_fu_38_fb_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Mat2Array_fu_38_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state1_ignore_call3 : BOOLEAN;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_state1 : BOOLEAN;

    component Mat2Array IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        img_data_stream_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        img_data_stream_V_empty_n : IN STD_LOGIC;
        img_data_stream_V_read : OUT STD_LOGIC;
        fb_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        fb_ce0 : OUT STD_LOGIC;
        fb_we0 : OUT STD_LOGIC;
        fb_d0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    grp_Mat2Array_fu_38 : component Mat2Array
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_Mat2Array_fu_38_ap_start,
        ap_done => grp_Mat2Array_fu_38_ap_done,
        ap_idle => grp_Mat2Array_fu_38_ap_idle,
        ap_ready => grp_Mat2Array_fu_38_ap_ready,
        img_data_stream_V_dout => img_data_stream_V_dout,
        img_data_stream_V_empty_n => img_data_stream_V_empty_n,
        img_data_stream_V_read => grp_Mat2Array_fu_38_img_data_stream_V_read,
        fb_address0 => grp_Mat2Array_fu_38_fb_address0,
        fb_ce0 => grp_Mat2Array_fu_38_fb_ce0,
        fb_we0 => grp_Mat2Array_fu_38_fb_we0,
        fb_d0 => grp_Mat2Array_fu_38_fb_d0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((grp_Mat2Array_fu_38_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_Mat2Array_fu_38_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_Mat2Array_fu_38_ap_start_reg <= ap_const_logic_0;
            else
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_Mat2Array_fu_38_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_Mat2Array_fu_38_ap_ready = ap_const_logic_1)) then 
                    grp_Mat2Array_fu_38_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, grp_Mat2Array_fu_38_ap_done, ap_CS_fsm_state2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_Mat2Array_fu_38_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state1_ignore_call3_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1_ignore_call3 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, grp_Mat2Array_fu_38_ap_done, ap_CS_fsm_state2)
    begin
        if (((grp_Mat2Array_fu_38_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_Mat2Array_fu_38_ap_done, ap_CS_fsm_state2)
    begin
        if (((grp_Mat2Array_fu_38_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    fb_address0 <= grp_Mat2Array_fu_38_fb_address0;
    fb_ce0 <= grp_Mat2Array_fu_38_fb_ce0;
    fb_d0 <= grp_Mat2Array_fu_38_fb_d0;
    fb_we0 <= grp_Mat2Array_fu_38_fb_we0;
    grp_Mat2Array_fu_38_ap_start <= grp_Mat2Array_fu_38_ap_start_reg;

    img_data_stream_V_read_assign_proc : process(grp_Mat2Array_fu_38_img_data_stream_V_read, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            img_data_stream_V_read <= grp_Mat2Array_fu_38_img_data_stream_V_read;
        else 
            img_data_stream_V_read <= ap_const_logic_0;
        end if; 
    end process;

end behav;
